spring.application.name=prototipo
server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5432/shensei
spring.datasource.username=postgres
spring.datasource.password=nelson15
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=core

# JWT settings
jwt.secret=WllXTnd2M0JndWJkZVJWekR0NWE4dDdnOW5rMloyVVFPTTJONmEzUjZiMjkzVDI1M1ZHOWpNMnR2YW1SaGJtOXljem9UTVU1V1FVMTURV0ZOSljIEyVN3BsUnpaVVIxTlNJaklrSkxa==
jwt.expiration-ms=3600000

# CORS settings
cors.allowed-origins=http://localhost:5173,http://localhost:5174

# Transfer token settings (segundos)
transfer.token.ttl-seconds=300

# Mail settings (ajustar con tu proveedor SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username={correo}
spring.mail.password={contrasenia}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
